version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-test
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass!123"  
      MSSQL_PID: "Developer"
    ports:
      - "7102:1433"  
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sqlnet

volumes:
  sql_data:

networks:
  sqlnet:
    driver: bridge